<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Lys</string>
    <key>scopeName</key>
    <string>source.lys</string>
    <key>fileTypes</key>
    <array>
      <string>lys</string>
    </array>
    <key>uuid</key>
    <string>1036f296-f34d-4f64-87d9-94fcfc477ea5</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>match</key>
        <string>^\s*(package)\b(?:\s*([^ ;$]+)\s*)?</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.lys</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.package.lys</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>include</key>
        <string>#imports</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#statements</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>impl</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;!::)(?=\b(?:impl)\b)</string>
        <key>end</key>
        <string>(?=$|\})</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(impl)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.type.lys</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=&lt;|\{|\(|:|$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>name</key>
                <string>entity.name.type.type.lys</string>
                <key>match</key>
                <string>\w+</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>&lt;</string>
            <key>end</key>
            <string>&gt;</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#generics</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>end</key>
            <string>\}</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#statements</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>wasm</key>
      <dict>
        <key>begin</key>
        <string>(?=(?:%wasm)\b)</string>
        <key>end</key>
        <string>(?=$|\})</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(%wasm)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.lys</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>end</key>
            <string>\}</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#wasm_string</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#wasm_constants</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#wasm_keywords</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#wasm_variables</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>structs</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;!::)(?=\b(?:struct)\b)</string>
        <key>end</key>
        <string>(?=$|\})</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(struct)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.class.lys</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=&lt;|\{|\(|:|$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>name</key>
                <string>entity.name.type.lys</string>
                <key>match</key>
                <string>\w+</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>&lt;</string>
            <key>end</key>
            <string>&gt;</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#generics</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\(</string>
            <key>end</key>
            <string>\)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#parameters</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.block.lys</string>
            <key>begin</key>
            <string>/\*</string>
            <key>end</key>
            <string>\*/</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.lys</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\s*((//).*$\n?)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>comment.line.double-slash.lys</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.lys</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.language.lys</string>
            <key>match</key>
            <string>\b(true|false)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.numeric.lys</string>
            <key>match</key>
            <string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)([LlFf])?\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.other.lys</string>
            <key>match</key>
            <string>\b([A-Z][A-Z0-9_]+)\b</string>
          </dict>
        </array>
      </dict>
      <key>expressions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\(</string>
            <key>end</key>
            <string>\)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expressions</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#wasm</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#types</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
        </array>
      </dict>
      <key>functions</key>
      <dict>
        <key>begin</key>
        <string>(?=\s*\b(?:fun)\b)</string>
        <key>end</key>
        <string>(?=$|\})</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(fun)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.function.lys</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\()</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>(\w+|\|\||&amp;&amp;|&amp;|\||\+\+|\-\-|\+|\-|==|!=|==|!==|&lt;=|&gt;=|&lt;&lt;|&gt;&gt;&gt;|&gt;&gt;|&lt;|&gt;|/|\*|\*\*|%|~|\^)</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.function.lys</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>begin</key>
                <string>&lt;</string>
                <key>end</key>
                <string>&gt;</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#generics</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\(</string>
            <key>end</key>
            <string>\)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#parameters</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?=:)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.declaration.lys</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?={|=|$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>end</key>
            <string>(?=\})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#statements</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(=)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.lys</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expressions</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>generics</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?=:)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.declaration.lys</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=,|&gt;)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>name</key>
            <string>storage.type.generic.lys</string>
            <key>match</key>
            <string>\w+</string>
          </dict>
        </array>
      </dict>
      <key>imports</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>^\s*(import)\s+[^ $]+\s+(as)?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.lys</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.lys</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>storage.modifier.lys</string>
            <key>match</key>
            <string>\b(var|val|public|private|protected|abstract|final|sealed|enum|open|attribute|annotation|override|inline|vararg|in|out|internal|tailrec|operator|infix|const|yield|typealias|typeof|reified|suspend)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.lys</string>
            <key>match</key>
            <string>\b(if|else|while|for|loop|case|do|return|when|where|break|continue|match)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.lys</string>
            <key>match</key>
            <string>(%stack|%injected)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.lys</string>
            <key>match</key>
            <string>\b(is|as)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.comparison.lys</string>
            <key>match</key>
            <string>(==|!=|==|!==|&lt;=|&gt;=|&lt;&lt;|&gt;&gt;&gt;|&gt;&gt;|&lt;|&gt;)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.lys</string>
            <key>match</key>
            <string>(=)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>source.lys</string>
            <key>match</key>
            <string>(::)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.arithmetic.lys</string>
            <key>match</key>
            <string>(\-|\+|\*|\/|%|~|^)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.logical.lys</string>
            <key>match</key>
            <string>(!|&amp;&amp;|\|\|)</string>
          </dict>
        </array>
      </dict>
      <key>parameters</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?=:)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.declaration.lys</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=,|\)|=)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(=)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.declaration.lys</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=,|\))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expressions</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>name</key>
            <string>variable.parameter.function.lys</string>
            <key>match</key>
            <string>\w+</string>
          </dict>
        </array>
      </dict>
      <key>statements</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#typedefs</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#structs</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#impl</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#functions</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#variables</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expressions</string>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>string.quoted.third.lys</string>
            <key>begin</key>
            <string>"""</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.lys</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"""</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.lys</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>variable.parameter.template.lys</string>
                <key>match</key>
                <string>(\$\w+|\$\{[^\}]+\})</string>
              </dict>
              <dict>
                <key>name</key>
                <string>constant.character.escape.lys</string>
                <key>match</key>
                <string>\\.</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>string.quoted.double.lys</string>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.lys</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.lys</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>(\$\w+|\$\{[^\}]+\})</string>
                <key>name</key>
                <string>variable.parameter.template.lys</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\\.</string>
                <key>name</key>
                <string>constant.character.escape.lys</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>string.quoted.single.lys</string>
            <key>begin</key>
            <string>'</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.lys</string>
              </dict>
            </dict>
            <key>end</key>
            <string>'</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.lys</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>constant.character.escape.lys</string>
                <key>match</key>
                <string>\\.</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>string.quoted.single.lys</string>
            <key>begin</key>
            <string>`</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.lys</string>
              </dict>
            </dict>
            <key>end</key>
            <string>`</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.lys</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>typedefs</key>
      <dict>
        <key>begin</key>
        <string>(?=\s*(?:type|enum))</string>
        <key>end</key>
        <string>(?=\{?$)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>storage.type.class.lys</string>
            <key>match</key>
            <string>\b(type|enum)\b</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([a-zA-Z][a-zA-Z0-9_]*)</string>
            <key>name</key>
            <string>entity.name.type.lys</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>&lt;</string>
            <key>end</key>
            <string>&gt;</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#generics</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#expressions</string>
          </dict>
        </array>
      </dict>
      <key>types</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>storage.type.buildin.lys</string>
            <key>match</key>
            <string>(%struct|%stack|%injected)\b</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(:\s*)([A-Z][A-Za-z0-9_]*)&lt;\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.declaration.lys</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>support.type.buildin.collection.lys</string>
              </dict>
            </dict>
            <key>end</key>
            <string>&gt;</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\w+&lt;</string>
            <key>end</key>
            <string>&gt;</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>end</key>
            <string>\}</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#statements</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\(</string>
            <key>end</key>
            <string>\)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>(:\s*)([A-Z][A-Za-z0-9_]*)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.declaration.lys</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>support.type.lys</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(:\s*)([a-z][A-Za-z0-9_]*)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.declaration.lys</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>support.type.buildin.lys</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.declaration.lys</string>
            <key>match</key>
            <string>(-&gt;)</string>
          </dict>
        </array>
      </dict>
      <key>variables</key>
      <dict>
        <key>begin</key>
        <string>(?=\s*\b(?:var|val)\b)</string>
        <key>end</key>
        <string>(?=:|=|(\b(by)\b)|$)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(var|val)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.var.lys</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=:|=|(\b(by)\b)|$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>&lt;</string>
                <key>end</key>
                <string>&gt;</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#generics</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>match</key>
                <string>([\.&lt;\?&gt;\w]+\.)?(\$?\w+)</string>
                <key>captures</key>
                <dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.variable.lys</string>
                  </dict>
                </dict>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?=:)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.declaration.lys</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?==|$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(by)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.lys</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expressions</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(=)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.lys</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expressions</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>wasm_string</key>
      <dict>
        <key>name</key>
        <string>string.quoted.double.wasm</string>
        <key>begin</key>
        <string>(?&lt;!\\)(")</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.wasm</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(")</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.wasm</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>constant.character.escape.wasm</string>
          </dict>
        </array>
      </dict>
      <key>wasm_constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)([LlFf])?\b</string>
            <key>name</key>
            <string>support.constant.wasm</string>
          </dict>
        </array>
      </dict>
      <key>wasm_keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(block|if|then|else|end)\b</string>
            <key>name</key>
            <string>keyword.control.conditional.wasm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(local)\b</string>
            <key>name</key>
            <string>keyword.control.local.wasm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(loop)\b</string>
            <key>name</key>
            <string>keyword.control.loop.wasm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(unreachable|nop|br|br_if|br_if_table|return|call|call_indirect|drop)\b</string>
            <key>name</key>
            <string>keyword.control.flow.wasm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(get_local|set_local|tee_local|get_global|set_global|const)\b</string>
            <key>name</key>
            <string>support.function.wasm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(i32|i64|f32|f64)\.([a-zA-Z0-9_./]*)?\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type.datatype.wasm</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>support.function.lys</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>wasm_variables</key>
      <dict>
        <key>name</key>
        <string>variable.other.wasm</string>
        <key>match</key>
        <string>(?&lt;=\s)\$\S+\s</string>
      </dict>
    </dict>
  </dict>
</plist>