from pygments.lexer import RegexLexer, bygroups
from pygments.token import *

import re

__all__=['LysLexer']

class LysLexer(RegexLexer):
    name = 'Lys'
    aliases = ['lys']
    filenames = ['*.lys']
    flags = re.MULTILINE | re.UNICODE

    tokens = {
        'root' : [
            (u'(/\\*)', bygroups(Comment.Multiline), 'multi_line_comment__1'),
            (u'(//.*)', bygroups(Comment)),
            (u'(\\\"\\\")', bygroups(String)),
            (u'(\\\")', bygroups(String), 'literals__1'),
            (u'(-)?(\\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\\.?[0-9]*)|(\\.[0-9]+))((e|E)(\\+|-)?[0-9]+)?)([LlFf])?\\b)', bygroups(Number)),
            (u'(\\b(true|false)\\b)', bygroups(Keyword.Constant)),
            (u'\\b(fun)(\\s+)(\\w+|\\|\\||&&|&|\\||\\+\\+|\\-\\-|\\+|\\-|==|!=|==|!==|<=|>=|<<|>>>|>>|<|>|/|\\*|\\*\\*|%|~|\\^)(?:\\s*(\\()?)', bygroups(Keyword.Declaration, Generic, Name.Function, Punctuation), 'main__1'),
            (u'\\b(val|var)(\\s+)([A-Z][A-Z0-9_]*)', bygroups(Keyword.Declaration, Generic, Name.Constant)),
            (u'\\b(val|var)(\\s+)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Keyword.Declaration, Generic, Name.Variable)),
            (u'\\b(import)(\\s+)((?:[A-Za-z$_][A-Za-z0-9$_]*::)+)', bygroups(Keyword.Declaration, Generic, Name.Namespace)),
            (u'\\b(import)(\\s+)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Keyword.Declaration, Generic, Name.Namespace)),
            (u'\\b(impl)(\\s+)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Keyword.Declaration, Generic, Name.Class)),
            (u'\\b(type)(\\s+)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Keyword.Declaration, Generic, Name.Class)),
            (u'\\b(enum)(\\s+)([A-Za-z$_][A-Za-z0-9$_]*)(?:\\s+(\\{)?)', bygroups(Keyword.Declaration, Generic, Name.Class, Punctuation), 'main__2'),
            (u'(%wasm)(\\s*)(\\{)', bygroups(Keyword, Generic, Punctuation), 'main__4'),
            (u'(%injected)\\b', bygroups(Keyword.Declaration)),
            (u'(%stack)(\\s*)(\\{)', bygroups(Keyword, Generic, Punctuation), 'main__5'),
            (u'\\b(struct)(\\s+)([A-Za-z$_][A-Za-z0-9$_]*)(?:\\s*(\\()?)', bygroups(Keyword.Declaration, Generic, Name.Class, Punctuation), 'main__6'),
            (u'\\b(if|match|case|fun|else|loop|continue|break)\\b', bygroups(Keyword)),
            (u'(?:%inline|%struct|\\b(private))', bygroups(Keyword)),
            (u'((?:[A-Za-z$_][A-Za-z0-9$_]*::)+)', bygroups(Name.Namespace)),
            (u'(\\->)', bygroups(Punctuation)),
            (u'(\\.\\^)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Punctuation, Name.Constant)),
            (u'(\\.\\^|\\.)', bygroups(Punctuation)),
            (u'(\\|\\||&&|&|\\||\\+\\+|\\-\\-|\\+|\\-|==|!=|==|!==|<=|>=|<<|>>>|>>|<|>|/|\\*|\\*\\*|%|~|\\^|!)', bygroups(Operator)),
            (u'([:|&]\\s*)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Punctuation, Name.Variable.Class)),
            (u'(\\b(?:is|as)\\s+)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Keyword, Name.Variable.Class)),
            (u'([:|&]\\s*\\()', bygroups(Punctuation), 'types__1'),
            (u'\\b([A-Z][A-Z0-9_]*)\\b', bygroups(Name.Constant)),
            (u'([A-Za-z$_][A-Za-z0-9$_]*)(\\()', bygroups(Name.Function, Punctuation), 'main__7'),
            (u'\\b([A-Z][A-Za-z0-9$_]*)\\b', bygroups(Name.Variable.Class)),
            (u'([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Name.Variable)),
            (u'(=)', bygroups(Punctuation)),
            (u'(\\{)', bygroups(Punctuation), 'main__8'),
            (u'(\\()', bygroups(Punctuation), 'main__9'),
            (u'(#\\[)', bygroups(Name.Decorator), 'decorators__1'),
            (u'([^\\s\\n\\r])', bygroups(Generic.Error)),
            ('(\n|\r|\r\n)', String),
            ('.', String),
        ], 
        'decorators__1' : [
            (u'(\\\"\\\")', bygroups(String)),
            (u'(\\\")', bygroups(String), 'literals__1'),
            (u'(-)?(\\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\\.?[0-9]*)|(\\.[0-9]+))((e|E)(\\+|-)?[0-9]+)?)([LlFf])?\\b)', bygroups(Number)),
            (u'(\\b(true|false)\\b)', bygroups(Keyword.Constant)),
            (u'([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Name.Decorator)),
            ('(\n|\r|\r\n)', String),
            ('.', String),
        ], 
        'literals__1' : [
            ('(\n|\r|\r\n)', String),
            ('.', String),
        ], 
        'main__1' : [
            (u'(,)', bygroups(Punctuation)),
            (u'([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Name.Variable)),
            (u'([:|&]\\s*)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Punctuation, Name.Variable.Class)),
            (u'(\\b(?:is|as)\\s+)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Keyword, Name.Variable.Class)),
            (u'([:|&]\\s*\\()', bygroups(Punctuation), 'types__1'),
            ('(\n|\r|\r\n)', String),
            ('.', String),
        ], 
        'main__2' : [
            (u'([A-Za-z$_][A-Za-z0-9$_]*)(\\s*\\()', bygroups(Name.Class, Punctuation), 'main__3'),
            (u'([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Name.Class)),
            ('(\n|\r|\r\n)', String),
            ('.', String),
        ], 
        'main__3' : [
            (u'(,)', bygroups(Punctuation)),
            (u'([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Name.Variable)),
            (u'([:|&]\\s*)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Punctuation, Name.Variable.Class)),
            (u'(\\b(?:is|as)\\s+)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Keyword, Name.Variable.Class)),
            (u'([:|&]\\s*\\()', bygroups(Punctuation), 'types__1'),
            ('(\n|\r|\r\n)', String),
            ('.', String),
        ], 
        'main__4' : [
            (u'(/\\*)', bygroups(Comment.Multiline), 'multi_line_comment__1'),
            (u'(//.*)', bygroups(Comment)),
            (u'(-)?(\\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\\.?[0-9]*)|(\\.[0-9]+))((e|E)(\\+|-)?[0-9]+)?)([LlFf])?\\b)', bygroups(Number)),
            (u'\\b(i32|i64|f32|f64)\\b', bygroups(Name.Variable.Class)),
            (u'(\\$)((?:[A-Za-z$_][A-Za-z0-9$_]*::)+)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Name.Namespace, Name.Namespace, Name.Variable)),
            (u'(\\$)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Name.Variable)),
            (u'(([\\w\\./]+)\\b)', bygroups(String)),
            (u'(\\()(?:([\\w\\./$]+)?\\b)', bygroups(Punctuation, Keyword), 'wasm__1'),
            ('(\n|\r|\r\n)', String),
            ('.', String),
        ], 
        'main__5' : [
            (u'([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Name.Constant)),
            (u'(=)', bygroups(Punctuation)),
            (u'(\\\"\\\")', bygroups(String)),
            (u'(\\\")', bygroups(String), 'literals__1'),
            (u'(-)?(\\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\\.?[0-9]*)|(\\.[0-9]+))((e|E)(\\+|-)?[0-9]+)?)([LlFf])?\\b)', bygroups(Number)),
            (u'(\\b(true|false)\\b)', bygroups(Keyword.Constant)),
            ('(\n|\r|\r\n)', String),
            ('.', String),
        ], 
        'main__6' : [
            (u'(,)', bygroups(Punctuation)),
            (u'([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Name.Variable)),
            (u'([:|&]\\s*)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Punctuation, Name.Variable.Class)),
            (u'(\\b(?:is|as)\\s+)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Keyword, Name.Variable.Class)),
            (u'([:|&]\\s*\\()', bygroups(Punctuation), 'types__1'),
            ('(\n|\r|\r\n)', String),
            ('.', String),
        ], 
        'main__7' : [
            (u'(,)', bygroups(Punctuation)),
            (u'(/\\*)', bygroups(Comment.Multiline), 'multi_line_comment__1'),
            (u'(//.*)', bygroups(Comment)),
            (u'(\\\"\\\")', bygroups(String)),
            (u'(\\\")', bygroups(String), 'literals__1'),
            (u'(-)?(\\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\\.?[0-9]*)|(\\.[0-9]+))((e|E)(\\+|-)?[0-9]+)?)([LlFf])?\\b)', bygroups(Number)),
            (u'(\\b(true|false)\\b)', bygroups(Keyword.Constant)),
            (u'\\b(fun)(\\s+)(\\w+|\\|\\||&&|&|\\||\\+\\+|\\-\\-|\\+|\\-|==|!=|==|!==|<=|>=|<<|>>>|>>|<|>|/|\\*|\\*\\*|%|~|\\^)(?:\\s*(\\()?)', bygroups(Keyword.Declaration, Generic, Name.Function, Punctuation), 'main__1'),
            (u'\\b(val|var)(\\s+)([A-Z][A-Z0-9_]*)', bygroups(Keyword.Declaration, Generic, Name.Constant)),
            (u'\\b(val|var)(\\s+)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Keyword.Declaration, Generic, Name.Variable)),
            (u'\\b(import)(\\s+)((?:[A-Za-z$_][A-Za-z0-9$_]*::)+)', bygroups(Keyword.Declaration, Generic, Name.Namespace)),
            (u'\\b(import)(\\s+)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Keyword.Declaration, Generic, Name.Namespace)),
            (u'\\b(impl)(\\s+)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Keyword.Declaration, Generic, Name.Class)),
            (u'\\b(type)(\\s+)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Keyword.Declaration, Generic, Name.Class)),
            (u'\\b(enum)(\\s+)([A-Za-z$_][A-Za-z0-9$_]*)(?:\\s+(\\{)?)', bygroups(Keyword.Declaration, Generic, Name.Class, Punctuation), 'main__2'),
            (u'(%wasm)(\\s*)(\\{)', bygroups(Keyword, Generic, Punctuation), 'main__4'),
            (u'(%injected)\\b', bygroups(Keyword.Declaration)),
            (u'(%stack)(\\s*)(\\{)', bygroups(Keyword, Generic, Punctuation), 'main__5'),
            (u'\\b(struct)(\\s+)([A-Za-z$_][A-Za-z0-9$_]*)(?:\\s*(\\()?)', bygroups(Keyword.Declaration, Generic, Name.Class, Punctuation), 'main__6'),
            (u'\\b(if|match|case|fun|else|loop|continue|break)\\b', bygroups(Keyword)),
            (u'(?:%inline|%struct|\\b(private))', bygroups(Keyword)),
            (u'((?:[A-Za-z$_][A-Za-z0-9$_]*::)+)', bygroups(Name.Namespace)),
            (u'(\\->)', bygroups(Punctuation)),
            (u'(\\.\\^)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Punctuation, Name.Constant)),
            (u'(\\.\\^|\\.)', bygroups(Punctuation)),
            (u'(\\|\\||&&|&|\\||\\+\\+|\\-\\-|\\+|\\-|==|!=|==|!==|<=|>=|<<|>>>|>>|<|>|/|\\*|\\*\\*|%|~|\\^|!)', bygroups(Operator)),
            (u'([:|&]\\s*)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Punctuation, Name.Variable.Class)),
            (u'(\\b(?:is|as)\\s+)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Keyword, Name.Variable.Class)),
            (u'([:|&]\\s*\\()', bygroups(Punctuation), 'types__1'),
            (u'\\b([A-Z][A-Z0-9_]*)\\b', bygroups(Name.Constant)),
            (u'([A-Za-z$_][A-Za-z0-9$_]*)(\\()', bygroups(Name.Function, Punctuation), 'main__7'),
            (u'\\b([A-Z][A-Za-z0-9$_]*)\\b', bygroups(Name.Variable.Class)),
            (u'([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Name.Variable)),
            (u'(=)', bygroups(Punctuation)),
            (u'(\\{)', bygroups(Punctuation), 'main__8'),
            (u'(\\()', bygroups(Punctuation), 'main__9'),
            (u'(#\\[)', bygroups(Name.Decorator), 'decorators__1'),
            (u'([^\\s\\n\\r])', bygroups(Generic.Error)),
            ('(\n|\r|\r\n)', String),
            ('.', String),
        ], 
        'main__8' : [
            (u'(/\\*)', bygroups(Comment.Multiline), 'multi_line_comment__1'),
            (u'(//.*)', bygroups(Comment)),
            (u'(\\\"\\\")', bygroups(String)),
            (u'(\\\")', bygroups(String), 'literals__1'),
            (u'(-)?(\\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\\.?[0-9]*)|(\\.[0-9]+))((e|E)(\\+|-)?[0-9]+)?)([LlFf])?\\b)', bygroups(Number)),
            (u'(\\b(true|false)\\b)', bygroups(Keyword.Constant)),
            (u'\\b(fun)(\\s+)(\\w+|\\|\\||&&|&|\\||\\+\\+|\\-\\-|\\+|\\-|==|!=|==|!==|<=|>=|<<|>>>|>>|<|>|/|\\*|\\*\\*|%|~|\\^)(?:\\s*(\\()?)', bygroups(Keyword.Declaration, Generic, Name.Function, Punctuation), 'main__1'),
            (u'\\b(val|var)(\\s+)([A-Z][A-Z0-9_]*)', bygroups(Keyword.Declaration, Generic, Name.Constant)),
            (u'\\b(val|var)(\\s+)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Keyword.Declaration, Generic, Name.Variable)),
            (u'\\b(import)(\\s+)((?:[A-Za-z$_][A-Za-z0-9$_]*::)+)', bygroups(Keyword.Declaration, Generic, Name.Namespace)),
            (u'\\b(import)(\\s+)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Keyword.Declaration, Generic, Name.Namespace)),
            (u'\\b(impl)(\\s+)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Keyword.Declaration, Generic, Name.Class)),
            (u'\\b(type)(\\s+)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Keyword.Declaration, Generic, Name.Class)),
            (u'\\b(enum)(\\s+)([A-Za-z$_][A-Za-z0-9$_]*)(?:\\s+(\\{)?)', bygroups(Keyword.Declaration, Generic, Name.Class, Punctuation), 'main__2'),
            (u'(%wasm)(\\s*)(\\{)', bygroups(Keyword, Generic, Punctuation), 'main__4'),
            (u'(%injected)\\b', bygroups(Keyword.Declaration)),
            (u'(%stack)(\\s*)(\\{)', bygroups(Keyword, Generic, Punctuation), 'main__5'),
            (u'\\b(struct)(\\s+)([A-Za-z$_][A-Za-z0-9$_]*)(?:\\s*(\\()?)', bygroups(Keyword.Declaration, Generic, Name.Class, Punctuation), 'main__6'),
            (u'\\b(if|match|case|fun|else|loop|continue|break)\\b', bygroups(Keyword)),
            (u'(?:%inline|%struct|\\b(private))', bygroups(Keyword)),
            (u'((?:[A-Za-z$_][A-Za-z0-9$_]*::)+)', bygroups(Name.Namespace)),
            (u'(\\->)', bygroups(Punctuation)),
            (u'(\\.\\^)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Punctuation, Name.Constant)),
            (u'(\\.\\^|\\.)', bygroups(Punctuation)),
            (u'(\\|\\||&&|&|\\||\\+\\+|\\-\\-|\\+|\\-|==|!=|==|!==|<=|>=|<<|>>>|>>|<|>|/|\\*|\\*\\*|%|~|\\^|!)', bygroups(Operator)),
            (u'([:|&]\\s*)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Punctuation, Name.Variable.Class)),
            (u'(\\b(?:is|as)\\s+)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Keyword, Name.Variable.Class)),
            (u'([:|&]\\s*\\()', bygroups(Punctuation), 'types__1'),
            (u'\\b([A-Z][A-Z0-9_]*)\\b', bygroups(Name.Constant)),
            (u'([A-Za-z$_][A-Za-z0-9$_]*)(\\()', bygroups(Name.Function, Punctuation), 'main__7'),
            (u'\\b([A-Z][A-Za-z0-9$_]*)\\b', bygroups(Name.Variable.Class)),
            (u'([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Name.Variable)),
            (u'(=)', bygroups(Punctuation)),
            (u'(\\{)', bygroups(Punctuation), 'main__8'),
            (u'(\\()', bygroups(Punctuation), 'main__9'),
            (u'(#\\[)', bygroups(Name.Decorator), 'decorators__1'),
            (u'([^\\s\\n\\r])', bygroups(Generic.Error)),
            ('(\n|\r|\r\n)', String),
            ('.', String),
        ], 
        'main__9' : [
            (u'(,)', bygroups(Punctuation)),
            (u'(/\\*)', bygroups(Comment.Multiline), 'multi_line_comment__1'),
            (u'(//.*)', bygroups(Comment)),
            (u'(\\\"\\\")', bygroups(String)),
            (u'(\\\")', bygroups(String), 'literals__1'),
            (u'(-)?(\\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\\.?[0-9]*)|(\\.[0-9]+))((e|E)(\\+|-)?[0-9]+)?)([LlFf])?\\b)', bygroups(Number)),
            (u'(\\b(true|false)\\b)', bygroups(Keyword.Constant)),
            (u'\\b(fun)(\\s+)(\\w+|\\|\\||&&|&|\\||\\+\\+|\\-\\-|\\+|\\-|==|!=|==|!==|<=|>=|<<|>>>|>>|<|>|/|\\*|\\*\\*|%|~|\\^)(?:\\s*(\\()?)', bygroups(Keyword.Declaration, Generic, Name.Function, Punctuation), 'main__1'),
            (u'\\b(val|var)(\\s+)([A-Z][A-Z0-9_]*)', bygroups(Keyword.Declaration, Generic, Name.Constant)),
            (u'\\b(val|var)(\\s+)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Keyword.Declaration, Generic, Name.Variable)),
            (u'\\b(import)(\\s+)((?:[A-Za-z$_][A-Za-z0-9$_]*::)+)', bygroups(Keyword.Declaration, Generic, Name.Namespace)),
            (u'\\b(import)(\\s+)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Keyword.Declaration, Generic, Name.Namespace)),
            (u'\\b(impl)(\\s+)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Keyword.Declaration, Generic, Name.Class)),
            (u'\\b(type)(\\s+)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Keyword.Declaration, Generic, Name.Class)),
            (u'\\b(enum)(\\s+)([A-Za-z$_][A-Za-z0-9$_]*)(?:\\s+(\\{)?)', bygroups(Keyword.Declaration, Generic, Name.Class, Punctuation), 'main__2'),
            (u'(%wasm)(\\s*)(\\{)', bygroups(Keyword, Generic, Punctuation), 'main__4'),
            (u'(%injected)\\b', bygroups(Keyword.Declaration)),
            (u'(%stack)(\\s*)(\\{)', bygroups(Keyword, Generic, Punctuation), 'main__5'),
            (u'\\b(struct)(\\s+)([A-Za-z$_][A-Za-z0-9$_]*)(?:\\s*(\\()?)', bygroups(Keyword.Declaration, Generic, Name.Class, Punctuation), 'main__6'),
            (u'\\b(if|match|case|fun|else|loop|continue|break)\\b', bygroups(Keyword)),
            (u'(?:%inline|%struct|\\b(private))', bygroups(Keyword)),
            (u'((?:[A-Za-z$_][A-Za-z0-9$_]*::)+)', bygroups(Name.Namespace)),
            (u'(\\->)', bygroups(Punctuation)),
            (u'(\\.\\^)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Punctuation, Name.Constant)),
            (u'(\\.\\^|\\.)', bygroups(Punctuation)),
            (u'(\\|\\||&&|&|\\||\\+\\+|\\-\\-|\\+|\\-|==|!=|==|!==|<=|>=|<<|>>>|>>|<|>|/|\\*|\\*\\*|%|~|\\^|!)', bygroups(Operator)),
            (u'([:|&]\\s*)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Punctuation, Name.Variable.Class)),
            (u'(\\b(?:is|as)\\s+)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Keyword, Name.Variable.Class)),
            (u'([:|&]\\s*\\()', bygroups(Punctuation), 'types__1'),
            (u'\\b([A-Z][A-Z0-9_]*)\\b', bygroups(Name.Constant)),
            (u'([A-Za-z$_][A-Za-z0-9$_]*)(\\()', bygroups(Name.Function, Punctuation), 'main__7'),
            (u'\\b([A-Z][A-Za-z0-9$_]*)\\b', bygroups(Name.Variable.Class)),
            (u'([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Name.Variable)),
            (u'(=)', bygroups(Punctuation)),
            (u'(\\{)', bygroups(Punctuation), 'main__8'),
            (u'(\\()', bygroups(Punctuation), 'main__9'),
            (u'(#\\[)', bygroups(Name.Decorator), 'decorators__1'),
            (u'([^\\s\\n\\r])', bygroups(Generic.Error)),
            ('(\n|\r|\r\n)', String),
            ('.', String),
        ], 
        'multi_line_comment__1' : [
            ('(\n|\r|\r\n)', String),
            ('.', Comment.Multiline),
        ], 
        'types__1' : [
            (u'(,)', bygroups(Punctuation)),
            (u'([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Name.Variable.Class)),
            (u'([:|&]\\s*)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Punctuation, Name.Variable.Class)),
            (u'(\\b(?:is|as)\\s+)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Keyword, Name.Variable.Class)),
            (u'([:|&]\\s*\\()', bygroups(Punctuation), 'types__1'),
            ('(\n|\r|\r\n)', String),
            ('.', String),
        ], 
        'wasm__1' : [
            (u'(/\\*)', bygroups(Comment.Multiline), 'multi_line_comment__1'),
            (u'(//.*)', bygroups(Comment)),
            (u'(-)?(\\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\\.?[0-9]*)|(\\.[0-9]+))((e|E)(\\+|-)?[0-9]+)?)([LlFf])?\\b)', bygroups(Number)),
            (u'\\b(i32|i64|f32|f64)\\b', bygroups(Name.Variable.Class)),
            (u'(\\$)((?:[A-Za-z$_][A-Za-z0-9$_]*::)+)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Name.Namespace, Name.Namespace, Name.Variable)),
            (u'(\\$)([A-Za-z$_][A-Za-z0-9$_]*)', bygroups(Name.Variable)),
            (u'(([\\w\\./]+)\\b)', bygroups(String)),
            (u'(\\()(?:([\\w\\./$]+)?\\b)', bygroups(Punctuation, Keyword), 'wasm__1'),
            ('(\n|\r|\r\n)', String),
            ('.', String),
        ]
    }

