<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>lys</string>
   </array>
  <key>name</key>
  <string>lys</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.lys</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#multi_line_comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#literals</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>\b(fun)(\s+)(\w+|\|\||&amp;&amp;|&amp;|\||\+\+|\-\-|\+|\-|==|!=|==|!==|&lt;=|&gt;=|&lt;&lt;|&gt;&gt;&gt;|&gt;&gt;|&lt;|&gt;|/|\*|\*\*|%|~|\^)(?:\s*(\()?)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.function.lys.lys</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.lys</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.lys</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>punctuation.lys</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.lys</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(val|var)(\s+)([A-Z][A-Z0-9_]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.var.lys</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.lys</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>variable.other.constant.lys</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(val|var)(\s+)([A-Za-z\x{0024}_][A-Za-z0-9\x{0024}_]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.var.lys</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.lys</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.variable.lys</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(import)(\s+)((?:[A-Za-z\x{0024}_][A-Za-z0-9\x{0024}_]*::)+)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.var.lys</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.lys</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.module.lys</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(import)(\s+)([A-Za-z\x{0024}_][A-Za-z0-9\x{0024}_]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.var.lys</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.lys</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.module.lys</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(impl)(\s+)([A-Za-z\x{0024}_][A-Za-z0-9\x{0024}_]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.type.lys.lys</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.lys</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.class.lys</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(type)(\s+)([A-Za-z\x{0024}_][A-Za-z0-9\x{0024}_]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.type.lys.lys</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.lys</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.class.lys</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>\b(enum)(\s+)([A-Za-z\x{0024}_][A-Za-z0-9\x{0024}_]*)(?:\s+(\{)?)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.type.lys.lys</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.lys</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.class.lys</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>punctuation.lys</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.lys</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(%wasm)(\s*)(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.modifier.lys</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.lys</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.lys</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__4</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.lys</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(%injected)\b</string>
          <key>name</key>
          <string>storage.type.type.lys.lys</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(%stack)(\s*)(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.modifier.lys</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.lys</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.lys</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__5</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.lys</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>\b(struct)(\s+)([A-Za-z\x{0024}_][A-Za-z0-9\x{0024}_]*)(?:\s*(\()?)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.type.lys.lys</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.lys</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.class.lys</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>punctuation.lys</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__6</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.lys</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(if|match|case|fun|else|loop|continue|break)\b</string>
          <key>name</key>
          <string>keyword.lys</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?:%inline|%struct|\b(private))</string>
          <key>name</key>
          <string>storage.modifier.lys</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((?:[A-Za-z\x{0024}_][A-Za-z0-9\x{0024}_]*::)+)</string>
          <key>name</key>
          <string>entity.name.type.module.lys</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\-&gt;)</string>
          <key>name</key>
          <string>punctuation.lys</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\.\^)([A-Za-z\x{0024}_][A-Za-z0-9\x{0024}_]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.accessor.lys</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>variable.other.constant.lys</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\.\^|\.)</string>
          <key>name</key>
          <string>punctuation.accessor.lys</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\|\||&amp;&amp;|&amp;|\||\+\+|\-\-|\+|\-|==|!=|==|!==|&lt;=|&gt;=|&lt;&lt;|&gt;&gt;&gt;|&gt;&gt;|&lt;|&gt;|/|\*|\*\*|%|~|\^|!)</string>
          <key>name</key>
          <string>keyword.operator.lys</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#types</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b([A-Z][A-Z0-9_]*)\b</string>
          <key>name</key>
          <string>variable.other.constant.lys</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>([A-Za-z\x{0024}_][A-Za-z0-9\x{0024}_]*)(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.lys</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.lys</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__7</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.lys</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b([A-Z][A-Za-z0-9\x{0024}_]*)\b</string>
          <key>name</key>
          <string>variable.other.object.lys</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([A-Za-z\x{0024}_][A-Za-z0-9\x{0024}_]*)</string>
          <key>name</key>
          <string>variable.other.readwrite.ts.lys</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(=)</string>
          <key>name</key>
          <string>punctuation.lys</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.lys</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__8</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.lys</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.lys</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__9</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.lys</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#decorators</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>invalid.lys</string>
        </dict>
       </array>
    </dict>
    <key>decorators</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(#\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.block.preprocessor.lys</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#decorators__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.block.preprocessor.lys</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>decorators__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#literals</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([A-Za-z\x{0024}_][A-Za-z0-9\x{0024}_]*)</string>
          <key>name</key>
          <string>entity.other.attribute-name.lys</string>
        </dict>
       </array>
    </dict>
    <key>literals</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\&quot;\&quot;)</string>
          <key>name</key>
          <string>string.lys</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.lys</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.lys</string>
          <key>end</key>
          <string>([^\x{005c}]\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.lys</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b(true|false)\b)</string>
          <key>name</key>
          <string>constant.language.lys</string>
        </dict>
       </array>
    </dict>
    <key>literals__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.lys</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([A-Za-z\x{0024}_][A-Za-z0-9\x{0024}_]*)</string>
          <key>name</key>
          <string>variable.parameter.function.lys</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#types</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>([A-Za-z\x{0024}_][A-Za-z0-9\x{0024}_]*)(\s*\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.class.lys</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.lys</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.lys</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>([A-Za-z\x{0024}_][A-Za-z0-9\x{0024}_]*)</string>
          <key>name</key>
          <string>entity.name.class.lys</string>
        </dict>
       </array>
    </dict>
    <key>main__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.lys</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([A-Za-z\x{0024}_][A-Za-z0-9\x{0024}_]*)</string>
          <key>name</key>
          <string>variable.parameter.function.lys</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#types</string>
        </dict>
       </array>
    </dict>
    <key>main__4</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#wasm</string>
        </dict>
       </array>
    </dict>
    <key>main__5</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([A-Za-z\x{0024}_][A-Za-z0-9\x{0024}_]*)</string>
          <key>name</key>
          <string>variable.other.constant.lys</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(=)</string>
          <key>name</key>
          <string>punctuation.lys</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#literals</string>
        </dict>
       </array>
    </dict>
    <key>main__6</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.lys</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([A-Za-z\x{0024}_][A-Za-z0-9\x{0024}_]*)</string>
          <key>name</key>
          <string>variable.parameter.function.lys</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#types</string>
        </dict>
       </array>
    </dict>
    <key>main__7</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.lys</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__8</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__9</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.lys</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(/\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.block.documentation.lys</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.block.documentation.lys</string>
          <key>end</key>
          <string>(\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.block.documentation.lys</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>comment.lys</string>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(-)?(\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)([LlFf])?\b)</string>
          <key>name</key>
          <string>constant.numeric.lys</string>
        </dict>
       </array>
    </dict>
    <key>types</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([\x{003a}\x{007c}\x{0026}]\s*)([A-Za-z\x{0024}_][A-Za-z0-9\x{0024}_]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.lys</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>support.type.lys</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b(?:is|as)\s+)([A-Za-z\x{0024}_][A-Za-z0-9\x{0024}_]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.lys</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>support.type.lys</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>([\x{003a}\x{007c}\x{0026}]\s*\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.lys</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#types__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.lys</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>types__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.lys</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([A-Za-z\x{0024}_][A-Za-z0-9\x{0024}_]*)</string>
          <key>name</key>
          <string>support.type.lys</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#types</string>
        </dict>
       </array>
    </dict>
    <key>wasm</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#multi_line_comment</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(-)?(\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)([LlFf])?\b)</string>
          <key>name</key>
          <string>constant.numeric.lys</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(i32|i64|f32|f64)\b</string>
          <key>name</key>
          <string>support.type.lys</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\$)((?:[A-Za-z\x{0024}_][A-Za-z0-9\x{0024}_]*::)+)([A-Za-z\x{0024}_][A-Za-z0-9\x{0024}_]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.module.lys</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.module.lys</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>variable.other.readwrite.ts.lys</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\$)([A-Za-z\x{0024}_][A-Za-z0-9\x{0024}_]*)</string>
          <key>name</key>
          <string>variable.other.readwrite.ts.lys</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(([\w\.\x{002f}]+)\b)</string>
          <key>name</key>
          <string>string.lys</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()(?:([\w\.\x{002f}\x{0024}]+)?\b)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.lys</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>storage.modifier.lys</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#wasm__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.lys</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>wasm__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#wasm</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
